Previous Source/Source Code/Backend/StudentPickup/StudentPickup.MVC/Controllers/ManageKiosksController.cs
using System.Data.Entity;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using Repository.Pattern.UnitOfWork;
using StudentPickup.Data;
using StudentPickup.Service;

namespace StudentPickup.MVC.Controllers
{
    public class ManageKiosksController : Controller
    {
        private readonly IUnitOfWorkAsync _unitOfWorkAsync;
        private readonly IKioskService _kioskService;
        private readonly ISchoolService _schoolService;

        public ManageKiosksController(IUnitOfWorkAsync unitOfWorkAsync, IKioskService kioskService, ISchoolService schoolService)
        {
            _unitOfWorkAsync = unitOfWorkAsync;
            _kioskService = kioskService;
            _schoolService = schoolService;
        }
        // GET: Kiosks
        public async Task<ActionResult> Index()
        {
            var kiosks = _kioskService.Queryable().Include(k => k.ParentKiosk).Include(k => k.School);
            return View(await kiosks.ToListAsync());
        }

        // GET: Kiosks/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var kiosk = await _kioskService.FindAsync(id);
            if (kiosk == null)
            {
                return HttpNotFound();
            }
            return View(kiosk);
        }

        // GET: Kiosks/Create
        public ActionResult Create()
        {
            ViewBag.ParentKioskId = new SelectList(_kioskService.Queryable(), "KioskId", "Name");
            ViewBag.SchoolId = new SelectList(_schoolService.Queryable(), "SchoolId", "Name");
            return View();
        }

        // POST: Kiosks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "KioskId,ParentKioskId,ParentPortNumber,SchoolId,Name,Latitude,Longtitude")] Kiosk kiosk)
        {
            if (ModelState.IsValid)
            {
                _kioskService.Insert(kiosk);
                await _unitOfWorkAsync.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.ParentKioskId = new SelectList(_kioskService.Queryable(), "KioskId", "Name", kiosk.ParentKioskId);
            ViewBag.SchoolId = new SelectList(_schoolService.Queryable(), "SchoolId", "Name", kiosk.SchoolId);
            return View(kiosk);
        }

        // GET: Kiosks/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var kiosk = await _kioskService.FindAsync(id);
            if (kiosk == null)
            {
                return HttpNotFound();
            }
            ViewBag.ParentKioskId = new SelectList(_kioskService.Queryable(), "KioskId", "Name", kiosk.ParentKioskId);
            ViewBag.SchoolId = new SelectList(_schoolService.Queryable(), "SchoolId", "Name", kiosk.SchoolId);
            return View(kiosk);
        }

        // POST: Kiosks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "KioskId,ParentKioskId,ParentPortNumber,SchoolId,Name,Latitude,Longtitude")] Kiosk kiosk)
        {
            if (ModelState.IsValid)
            {
                _kioskService.Update(kiosk);
                await _unitOfWorkAsync.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.ParentKioskId = new SelectList(_kioskService.Queryable(), "KioskId", "Name", kiosk.ParentKioskId);
            ViewBag.SchoolId = new SelectList(_schoolService.Queryable(), "SchoolId", "Name", kiosk.SchoolId);
            return View(kiosk);
        }

        // GET: Kiosks/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var kiosk = await _kioskService.FindAsync(id);
            if (kiosk == null)
            {
                return HttpNotFound();
            }
            return View(kiosk);
        }

        // POST: Kiosks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            var kiosk = await _kioskService.FindAsync(id);
            _kioskService.Delete(kiosk);
            await _unitOfWorkAsync.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _unitOfWorkAsync.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Previous Source/Source Code/Backend/StudentPickup/StudentPickup.MVC/Controllers/ManageSchoolsController.cs
using System.Data.Entity;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using Repository.Pattern.UnitOfWork;
using StudentPickup.Data;
using StudentPickup.Service;

namespace StudentPickup.MVC.Controllers
{
    public class ManageSchoolsController : Controller
    {
        private readonly IUnitOfWorkAsync _unitOfWorkAsync;
        private readonly ISchoolService _schoolService;
        private readonly IStateService _stateService;

        public ManageSchoolsController(IUnitOfWorkAsync unitOfWorkAsync, ISchoolService schoolService, IStateService stateService)
        {
            _unitOfWorkAsync = unitOfWorkAsync;
            _schoolService = schoolService;
            _stateService = stateService;
        }

        // GET: ManageSchools
        public async Task<ActionResult> Index()
        {
            var schools = _schoolService.Queryable().Include(s => s.State);
            return View(await schools.ToListAsync());
        }

        // GET: ManageSchools/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var school = await _schoolService.Queryable().Include(s => s.State).SingleOrDefaultAsync(s => s.SchoolId == id);
            if (school == null)
            {
                return HttpNotFound();
            }
            return View(school);
        }

        // GET: ManageSchools/Create
        public ActionResult Create()
        {
            ViewBag.StateId = new SelectList(_stateService.Queryable(), "StateId", "Name");
            return View();
        }

        // POST: ManageSchools/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "SchoolId,Name,Address,ContactName,ContactEmail,ContactNumber,StateId,Latitude,Longtitude")] School school)
        {
            if (ModelState.IsValid)
            {
                _schoolService.Insert(school);
                await _unitOfWorkAsync.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.StateId = new SelectList(_stateService.Queryable(), "StateId", "Name", school.StateId);
            return View(school);
        }

        // GET: ManageSchools/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var school = await _schoolService.Queryable().Include(s => s.State).SingleOrDefaultAsync(s => s.SchoolId == id);
            if (school == null)
            {
                return HttpNotFound();
            }
            ViewBag.StateId = new SelectList(_stateService.Queryable(), "StateId", "Name", school.StateId);
            return View(school);
        }

        // POST: ManageSchools/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "SchoolId,Name,Address,ContactName,ContactEmail,ContactNumber,StateId,Latitude,Longtitude")] School school)
        {
            if (ModelState.IsValid)
            {
                _schoolService.Update(school);
                await _unitOfWorkAsync.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.StateId = new SelectList(_stateService.Queryable(), "StateId", "Name", school.StateId);
            return View(school);
        }

        // GET: ManageSchools/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var school = await _schoolService.Queryable().Include(s => s.State).SingleOrDefaultAsync(s => s.SchoolId == id);
            if (school == null)
            {
                return HttpNotFound();
            }
            return View(school);
        }

        // POST: ManageSchools/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            var school = await _schoolService.FindAsync(id);
            _schoolService.Delete(school);
            await _unitOfWorkAsync.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _unitOfWorkAsync.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Previous Source/Source Code/Backend/StudentPickup/StudentPickup.MVC/Controllers/ManageStudentsController.cs
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using Repository.Pattern.UnitOfWork;
using StudentPickup.Data;
using StudentPickup.Service;

namespace StudentPickup.MVC.Controllers
{
    public class ManageStudentsController : Controller
    {
        private readonly IUnitOfWorkAsync _unitOfWorkAsync;
        private readonly IStudentService _studentService;
        private readonly ISchoolService _schoolService;

        public ManageStudentsController(IUnitOfWorkAsync unitOfWorkAsync, IStudentService studentService, ISchoolService schoolService)
        {
            _unitOfWorkAsync = unitOfWorkAsync;
            _studentService = studentService;
            _schoolService = schoolService;
        }

        // GET: ManageStudents
        public async Task<ActionResult> Index()
        {
            var students = _studentService.Queryable().Include(s => s.School);
            return View(await students.ToListAsync());
        }

        // GET: ManageStudents/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var student = await _studentService.Queryable().Include(s => s.School).SingleOrDefaultAsync(s => s.StudentId == id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // GET: ManageStudents/Create
        public ActionResult Create()
        {
            ViewBag.SchoolId = new SelectList(_schoolService.Queryable(), "SchoolId", "Name");
            return View();
        }

        // POST: ManageStudents/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "StudentId,StudentSchoolId,RFID,SchoolId,MobileAppId,MobileNumber,GivenName,CommonName,FamilyName,DateOfBirth")] Student student)
        {
            if (ModelState.IsValid)
            {
                _studentService.Insert(student);
                await _unitOfWorkAsync.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.SchoolId = new SelectList(_schoolService.Queryable(), "SchoolId", "Name", student.SchoolId);
            return View(student);
        }

        // GET: ManageStudents/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var student = await _studentService.Queryable().Include(s => s.School).SingleOrDefaultAsync(s => s.StudentId == id);
            if (student == null)
            {
                return HttpNotFound();
            }
            ViewBag.SchoolId = new SelectList(_schoolService.Queryable(), "SchoolId", "Name", student.SchoolId);
            return View(student);
        }

        // POST: ManageStudents/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "StudentId,StudentSchoolId,RFID,SchoolId,MobileAppId,MobileNumber,GivenName,CommonName,FamilyName,DateOfBirth")] Student student)
        {
            if (ModelState.IsValid)
            {
                _studentService.Update(student);
                await _unitOfWorkAsync.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.SchoolId = new SelectList(_schoolService.Queryable(), "SchoolId", "Name", student.SchoolId);
            return View(student);
        }

        // GET: ManageStudents/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var student = await _studentService.Queryable().Include(s => s.School).SingleOrDefaultAsync(s => s.StudentId == id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // POST: ManageStudents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            var student = await _studentService.FindAsync(id);
            _studentService.Delete(student);
            await _unitOfWorkAsync.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _unitOfWorkAsync.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Previous Source/Source Code/Backend/StudentPickup/StudentPickup.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SchoolSmart</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="~/Content/kendo/2015.2.624/kendo.common.min.css" />
    <link rel="stylesheet" href="~/Content/kendo/2015.2.624/kendo.default.min.css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <style type="text/css">
        .navbar-inverse .navbar-nav>li>a {
            color: #fff;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" style="background-color: #B8B5B5; border-color: #B8B5B5;">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("Index", "Home")" title="SchoolSmart Home" class="navbar-brand" style="padding-top: 5px; padding-bottom: 5px;">
                    <img src="~/Content/images/logo_shoolwise3.png" alt="SchoolSmart" style="height: 60px;"/>
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        @Html.ActionLink("Guardians", "Index", "ManageGuardians")
                    </li>
                    <li>
                        @Html.ActionLink("Students", "Index", "ManageStudents")
                    </li>
                    <li>
                        @Html.ActionLink("Schools", "Index", "ManageSchools")
                    </li>
                    <li>
                        @Html.ActionLink("Kiosks", "Index", "ManageKiosks")
                    </li>
                    <li>
                        @Html.ActionLink("Geo Zones", "Index", "ManageSchoolGeoZones")
                    </li>
                    <li>
                        @Html.ActionLink("Pickup Schedules", "Index", "ManagePickupSchedules")
                    </li>
                    <li>
                        @Html.ActionLink("Pickup Schedule Sessions", "Index", "ManagePickupScheduleSessions")
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - SchoolSmart</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/kendo/2015.2.624/kendo.core.min.js"></script>
    <script src="~/Scripts/kendo/2015.2.624/kendo.calendar.min.js"></script>
    <script src="~/Scripts/kendo/2015.2.624/kendo.popup.min.js"></script>
    <script src="~/Scripts/kendo/2015.2.624/kendo.datepicker.min.js"></script>
    <script src="~/Scripts/kendo/2015.2.624/kendo.userevents.min.js"></script>
    <script src="~/Scripts/kendo/2015.2.624/kendo.numerictextbox.min.js"></script>
    <script src="~/Scripts/kendo/2015.2.624/kendo.validator.min.js"></script>
    <script src="~/Scripts/kendo/2015.2.624/kendo.data.min.js"></script>
    <script src="~/Scripts/kendo/2015.2.624/kendo.binder.min.js"></script>
    <script src="~/Scripts/kendo/2015.2.624/kendo.editable.min.js"></script>
    <script src="~/Scripts/kendo/2015.2.624/kendo.listview.min.js"></script>
    <script src="~/Scripts/kendo/2015.2.624/kendo.popup.min.js"></script>
    <script src="~/Scripts/kendo/2015.2.624/kendo.list.min.js"></script>
    <script src="~/Scripts/kendo/2015.2.624/kendo.dropdownlist.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>