Previous Source/Source Code/Backend/StudentPickup/StudentPickup.MVC/Controllers/ManageSchoolGeoZonesController.cs
using System.Data.Entity;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using Repository.Pattern.UnitOfWork;
using StudentPickup.Data;
using StudentPickup.Service;

namespace StudentPickup.MVC.Controllers
{
    public class ManageSchoolGeoZonesController : Controller
    {
        private readonly IUnitOfWorkAsync _unitOfWorkAsync;
        private readonly IGeoZoneTypeService _geoZoneTypeService;
        private readonly ISchoolService _schoolService;
        private readonly ISchoolGeoZoneService _schoolGeoZoneService;
        private readonly IGeoZonePolygonPointService _geoZonePolygonPointService;

        public ManageSchoolGeoZonesController(IUnitOfWorkAsync unitOfWorkAsync, ISchoolGeoZoneService schoolGeoZoneService, ISchoolService schoolService, IGeoZoneTypeService geoZoneTypeService, IGeoZonePolygonPointService geoZonePolygonPointService)
        {
            _unitOfWorkAsync = unitOfWorkAsync;
            _schoolService = schoolService;
            _geoZoneTypeService = geoZoneTypeService;
            _geoZonePolygonPointService = geoZonePolygonPointService;
            _schoolGeoZoneService = schoolGeoZoneService;
        }
        // GET: ManageSchoolGeoZones
        public async Task<ActionResult> Index()
        {
            var schoolGeoZones = _schoolGeoZoneService.Queryable().Include(s => s.GeoZoneType).Include(s => s.School);
            return View(await schoolGeoZones.ToListAsync());
        }

        // GET: ManageSchoolGeoZones/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SchoolGeoZone schoolGeoZone = await _schoolGeoZoneService.FindAsync(id);
            if (schoolGeoZone == null)
            {
                return HttpNotFound();
            }
            return View(schoolGeoZone);
        }

        // GET: ManageSchoolGeoZones/Create
        public ActionResult Create()
        {
            ViewBag.GeoZoneTypeId = new SelectList(_geoZoneTypeService.Queryable(), "GeoZoneTypeId", "Name");
            ViewBag.SchoolId = new SelectList(_schoolService.Queryable(), "SchoolId", "Name");
            return View();
        }

        // POST: ManageSchoolGeoZones/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "SchoolGeoZoneId,GeoZoneTypeId,SchoolId,Name,GuardianMessage,Description,GeoZonePolygonPoints")] SchoolGeoZone schoolGeoZone)
        {
            if (ModelState.IsValid)
            {
                foreach (var geoZonePolygonPoint in schoolGeoZone.GeoZonePolygonPoints)
                {
                    _geoZonePolygonPointService.Insert(geoZonePolygonPoint);
                }
                _schoolGeoZoneService.Insert(schoolGeoZone);
                await _unitOfWorkAsync.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.GeoZoneTypeId = new SelectList(_geoZoneTypeService.Queryable(), "GeoZoneTypeId", "Name", schoolGeoZone.GeoZoneTypeId);
            ViewBag.SchoolId = new SelectList(_schoolService.Queryable(), "SchoolId", "Name", schoolGeoZone.SchoolId);
            return View(schoolGeoZone);
        }

        // GET: ManageSchoolGeoZones/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SchoolGeoZone schoolGeoZone = await _schoolGeoZoneService.FindAsync(id);
            if (schoolGeoZone == null)
            {
                return HttpNotFound();
            }
            ViewBag.GeoZoneTypeId = new SelectList(_geoZoneTypeService.Queryable(), "GeoZoneTypeId", "Name", schoolGeoZone.GeoZoneTypeId);
            ViewBag.SchoolId = new SelectList(_schoolService.Queryable(), "SchoolId", "Name", schoolGeoZone.SchoolId);
            return View(schoolGeoZone);
        }

        // POST: ManageSchoolGeoZones/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "SchoolGeoZoneId,GeoZoneTypeId,SchoolId,Name,GuardianMessage,Description")] SchoolGeoZone schoolGeoZone)
        {
            if (ModelState.IsValid)
            {
                _schoolGeoZoneService.Update(schoolGeoZone);
                await _unitOfWorkAsync.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.GeoZoneTypeId = new SelectList(_geoZoneTypeService.Queryable(), "GeoZoneTypeId", "Name", schoolGeoZone.GeoZoneTypeId);
            ViewBag.SchoolId = new SelectList(_schoolService.Queryable(), "SchoolId", "Name", schoolGeoZone.SchoolId);
            return View(schoolGeoZone);
        }

        // GET: ManageSchoolGeoZones/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SchoolGeoZone schoolGeoZone = await _schoolGeoZoneService.FindAsync(id);
            if (schoolGeoZone == null)
            {
                return HttpNotFound();
            }
            return View(schoolGeoZone);
        }

        // POST: ManageSchoolGeoZones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            SchoolGeoZone schoolGeoZone = await _schoolGeoZoneService.FindAsync(id);
            _schoolGeoZoneService.Delete(schoolGeoZone);
            await _unitOfWorkAsync.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _unitOfWorkAsync.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Previous Source/Source Code/Backend/StudentPickup/StudentPickup.MVC/Views/ManageSchoolGeoZones/Create.cshtml
@model StudentPickup.Data.SchoolGeoZone

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "ManageSchoolGeoZones", null, FormMethod.Post, new { @id = "form", @name = "form" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SchoolGeoZone</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.GeoZoneTypeId, "Geo Zone Type", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GeoZoneTypeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GeoZoneTypeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SchoolId, "School", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SchoolId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SchoolId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GuardianMessage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GuardianMessage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GuardianMessage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">
                Polygon Points
            </label>
            <div class="col-md-10">
                <div id="map_canvas" style="height: 450px;"></div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


@section scripts {
    <script src="~/Scripts/app/createSchoolGeoZone.js"></script>

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCDeRAmqs4yeTCuVF_-zMLyoyQDSYntQNU&signed_in=true&libraries=drawing&callback=initialize"
            async defer></script>
}

Previous Source/Source Code/Backend/StudentPickup/StudentPickup.MVC/Views/ManageSchoolGeoZones/Delete.cshtml
@model StudentPickup.Data.SchoolGeoZone

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SchoolGeoZone</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GuardianMessage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GuardianMessage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GeoZoneType.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GeoZoneType.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.School.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.School.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Previous Source/Source Code/Backend/StudentPickup/StudentPickup.MVC/Views/ManageSchoolGeoZones/Details.cshtml
@model StudentPickup.Data.SchoolGeoZone

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>SchoolGeoZone</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GuardianMessage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GuardianMessage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GeoZoneType.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GeoZoneType.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.School.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.School.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.SchoolGeoZoneId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Previous Source/Source Code/Backend/StudentPickup/StudentPickup.MVC/Views/ManageSchoolGeoZones/Edit.cshtml
@model StudentPickup.Data.SchoolGeoZone

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SchoolGeoZone</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.SchoolGeoZoneId)

        <div class="form-group">
            @Html.LabelFor(model => model.GeoZoneTypeId, "GeoZoneTypeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GeoZoneTypeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GeoZoneTypeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SchoolId, "SchoolId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SchoolId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SchoolId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GuardianMessage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GuardianMessage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GuardianMessage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Previous Source/Source Code/Backend/StudentPickup/StudentPickup.MVC/Views/ManageSchoolGeoZones/Index.cshtml
@model IEnumerable<StudentPickup.Data.SchoolGeoZone>

@{
    ViewBag.Title = "Manage Geo Zones";
}

<h2>Manage Geo Zones</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GuardianMessage)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GeoZoneType.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.School.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GuardianMessage)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GeoZoneType.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.School.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.SchoolGeoZoneId }) |
            @Html.ActionLink("Details", "Details", new { id=item.SchoolGeoZoneId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.SchoolGeoZoneId })
        </td>
    </tr>
}

</table>